_BASE_: "Base-RCNN-SAN-FPN.yaml"
MODEL:
  #WEIGHTS: "/home/kvargas/kian/code/pytorch_cnn/san-detectron2/SAN/exp/imagenet/san19_patchwise/model/model_best.pth"
  MASK_ON: False
  SAN:
    CONV_BODY : "SAN10_pairwise"
SOLVER:
  # IMS_PER_BATCH: 4
  # BASE_LR: 0.0125
  # CHECKPOINT_PERIOD : 2000
  # STEPS: (21000, 25000)
  # MAX_ITER: 27000
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "checkpoints/FRCN-SAN10-pairwise-3x"