_BASE_: "Base-RCNN-SAN-FPN.yaml"
MODEL:
  #WEIGHTS: "/home/kvargas/kian/code/pytorch_cnn/san-detectron2/SAN/exp/imagenet/san19_patchwise/model/model_best.pth"
  MASK_ON: False
  SAN:
    CONV_BODY : "SAN19_patchwise"
SOLVER:
  # BASE_LR: 0.0001
  CHECKPOINT_PERIOD : 2000
  STEPS: (8400, 10000)
  MAX_ITER: 10800
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000
OUTPUT_DIR: "checkpoints/FRCN-SAN19-patchwise-3x"