_BASE_: "Base-RCNN-SAN-FPN.yaml"
MODEL:
  #WEIGHTS: "/home/kvargas/kian/code/pytorch_cnn/san-detectron2/SAN/exp/imagenet/san10_pairwise/model/model_best.pth"
  MASK_ON: False
  SAN:
    CONV_BODY : "SAN10_pairwise"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "checkpoints/FRCN-SAN10-pairwise-3x"