_BASE_: "Base-RCNN-SAN-FPN.yaml"
MODEL:
  #WEIGHTS: "/home/kvargas/kian/code/pytorch_cnn/san-detectron2/SAN/exp/imagenet/san19_patchwise/model/model_best.pth"
  MASK_ON: True
  SAN:
    CONV_BODY : "SAN19_patchwise"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  CHECKPOINT_PERIOD : 3000
  STEPS: (17500, 20833)
  MAX_ITER: 22500
  # STEPS: (105000, 125000)
  # MAX_ITER: 135000
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000
OUTPUT_DIR: "checkpoints/MRCN-SAN19-patchwise-3x"
# INPUT:
#   MIN_SIZE_TRAIN: (224,)
