_BASE_: "Base-RCNN-SAN-FPN.yaml"
MODEL:
  #WEIGHTS: "/home/kvargas/kian/code/pytorch_cnn/san-detectron2/SAN/exp/imagenet/san19_patchwise/model/model_best.pth"
  MASK_ON: True
  SAN:
    CONV_BODY : "SAN10_pairwise"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  CHECKPOINT_PERIOD : 3000
  STEPS: (105000, 125000)
  MAX_ITER: 135000
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000
OUTPUT_DIR: "checkpoints/MRCN-SAN10-pairwise-3x"